#!/bin/bash

# Display the statement
echo "ONLY PROCEED if you have your Access Key ID, Secret Access Key, Region, and Output Format - you will have to get these from a swarmfarm aws admin."

# Ask if the user wants to proceed or exit
read -p "Do you want to proceed? press enter"


    # Install necessary packages and configure AWS CLI
    sudo apt install -y ca-certificates apt-transport-https
    echo "deb https://apt.swarmfarm.com focal main" | sudo tee /etc/apt/sources.list.d/swarmfarm.list
    curl https://apt.swarmfarm.com/pubkey.gpg | sudo apt-key add -
    sudo apt update
    sudo apt install -y awscli

read -p "You are about to configure aws-cli on your computer if you stuff this up just run aws-configure and enter the correct details"

aws configure

sudo apt install -y swarmfarm-swarmbot-ssh-client

sudo apt install -y swarmfarm-auth-login

sudo apt install -y swarmfarm-attachment-aliases

sudo apt install -y swarmfarm-can-log-tools



