#!/bin/bash

# Prompt the user to type "proceed" or "exit"
while true; do
  read -p "ONLY PROCEED if you have your 

  Access Key ID
  Secret Access Key

  It will ask for region and output format find them below.
 -------------------------
 | region: ap-southeast-2|
 | output format: json   |
 -------------------------

  If you stuff this up just run aws configure and enter the correct details. 

  You will have to get these from a swarmfarm aws admin.
  -----------------------------------------
  Type proceed and press enter to continue: " user_input
  # Convert user input to lowercase for case-insensitive comparison
  user_input_lc=$(echo "$user_input" | tr '[:upper:]' '[:lower:]')
  if [ "$user_input_lc" == "proceed" ]; then
    echo "Continuing..."
    break
  elif [ "$user_input_lc" == "exit" ]; then
    echo "Exiting..."
    exit 1
  else
    echo "Invalid input. Please type 'proceed' or 'exit'."
  fi
done

    # Install necessary packages and configure AWS CLI
    sudo apt install -y ca-certificates apt-transport-https
    echo "deb https://apt.swarmfarm.com focal main" | sudo tee /etc/apt/sources.list.d/swarmfarm.list
    curl https://apt.swarmfarm.com/pubkey.gpg | sudo apt-key add -
    sudo apt update
    sudo apt install -y awscli && aws configure




